start Migration to typescript
LiveDuo/destack pull request #14
Opened 2021-05-29 12:20 UTC by JcdeA

Typescript will help prevent future bugs, and will be useful anyways while developing.
This PR will also dynamically load components for the grapesjs editor, which improves speed vastly. 

The contentprovider component used to be over 200kbs, but now is only 3.4kbs.

2021-05-29 12:48 UTC, JcdeA commented
Shoot I forgot that I removed the part that injects tailwind from a cdn in the library..

In this pr it removes those and the user has to install tailwind themselves.

Actually, it might be  a better Idea to give the user a choice.. use tailwind from cdn if they're lazy, or install tailwind themselves for better performance.

There isn't any way to trigger postcss(in nextjs) to run without creating a postcss config file in the users nextjs app as far as I know.  (tailwind is a postcss plugin)

2021-05-30 04:26 UTC, JcdeA commented
![image](https://user-images.githubusercontent.com/31413538/120091943-77685900-c14a-11eb-8f36-5d95d796064a.png)
Right is before, Left is after this pr.
Massive improvement because it doesn't load all the components for the grapejs editor in production mode.

2021-06-01 10:47 UTC, JcdeA commented
Hmm, this doesn't seem to work with blitz.js very well..

Blitzjs's webpack isn't recognizing the grapes. Min-(hash).js as. Js file for some reason

2021-06-01 10:51 UTC, LiveDuo commented
> Hmm, this doesn't seem to work with blitz.js very well..
> 
> Blitzjs's webpack isn't recognizing the grapes. Min-(hash).js as. Js file for some reason

That's strange. I thought blitzjs was built on Next.js.

2021-06-01 10:52 UTC, LiveDuo commented
> ![image](https://user-images.githubusercontent.com/31413538/120091943-77685900-c14a-11eb-8f36-5d95d796064a.png)
> Right is before, Left is after this pr.
> Massive improvement because it doesn't load all the components for the grapejs editor in production mode.

Forgot to say. That improvement is huge! It makes attractive to SEO people and better position when the blogging system is ready!

2021-06-01 10:58 UTC, JcdeA commented
Yep! It used to load ALL of the tailblocks components even in production. We were just loading 250+kbs of unused code.

I just made it dynamically load grapes.js using es2020 dynamic imports.

2021-06-01 14:25 UTC, LiveDuo requested changes
I think we should add`.tsbuildinfo` (and `lib/destack/.tsbuildinfo`) and `.vscode` to `.gitignore`. Some like to have VSCode config commited into their repo to have a consistent work environment but since it's an open source project it might be better to let contributors choose their own config.

2021-06-01 14:25 UTC, LiveDuo commented on lib/destack/src/components/initEditor.tsx
> +  /*       const uploadFile = (e): void => {
I notice that `uploadFile` is broken (before this PR). 

Will fix it later and check these changes in depth later when I get to fix it.

2021-06-01 14:27 UTC, LiveDuo commented
I was thinking about TailwindCSS integration and what's the best way to go forward with it. For the time being it might be better to seperate Tailwind changes into a seperate PR.

There are a few things to consider further before moving on with that change. On the other hand Typescript support on the other hand seems good to go. Same with dynamically loading Grapes.js!

2021-06-01 14:43 UTC, JcdeA commented
> I think we should add`.tsbuildinfo` (and `lib/destack/.tsbuildinfo`) and `.vscode` to `.gitignore`. Some like to have VSCode config commited into the repo to have a consistent work environment but since it's an open source project it might be better to let contributors choose their own config.

Thanks!

2021-06-08 04:13 UTC, closed without merging

2021-06-08 04:13 UTC, JcdeA commented
see #18