Support multiple-pages
LiveDuo/destack pull request #32
Opened 2021-12-07 16:22 UTC by nikolas-con

Hey guys 👋, this is the implementation about supporting multiple pages. Following the suggested solutions  on comment  [https://github.com/LiveDuo/destack/issues/24#issuecomment-904067773](url)

2021-12-17 15:36 UTC, LiveDuo commented on lib/destack/src/components/react.tsx
>  const isDev = process.env.NODE_ENV !== 'production'
```suggestion
const isDev = '_self' in React.createElement('div')
```

2021-12-17 15:37 UTC, LiveDuo commented on lib/destack/src/components/react.tsx
> +const isDev = '_self' in React.createElement('div')
```suggestion
const isDev = process.env.NODE_ENV !== 'production'
```

2021-12-18 10:58 UTC, LiveDuo commented on lib/destack/server/props/index.ts
> +interface dataType {
We can import this from `types.d.ts` instead of declare it again.

2021-12-18 11:01 UTC, LiveDuo commented on lib/destack/server/api/handle.ts
> +    const folderPathExists = splitedPath.slice(0, splitedPath.length - 1).join('/')
```suggestion
    const folderPathExists = body.path.split('/').slice(0, -1).join('/')
```

2021-12-18 11:02 UTC, LiveDuo requested changes
Two small cosmetic changes and it's good to go!

2021-12-19 20:51 UTC, merged

2023-09-08 18:54 UTC, bradleytaftsmith commented
@LiveDuo @nikolas-con is there any instruction around for the usage of this feature? 

I read through issue #24 and the changes here, but couldn't really sort out how to implement multiple pages using destack.

Thanks for the awesome tool!

2023-09-09 07:08 UTC, LiveDuo commented
Hey @bradleytaftsmith,

You just need two Next.js pages like this one [main/pages/index.js](https://github.com/LiveDuo/destack-starter/blob/main/pages/index.js).

Say you want a `home` and a `about` page, you would need to create two files in the `pages`, one called `home.js` and one  called `about.js` and import destack in both.

Maybe I should add it to the docs at some point.

2023-09-09 19:45 UTC, bradleytaftsmith commented
ah, duh. It looks like you did actually have it in the Readme to some [here](https://github.com/LiveDuo/destack#multi-page-support). 

I didn't intuit that localhost:3000/my_page_name would get me to the editor, so I was having trouble finding it after duplicating and re-naming my `index.js`

Thanks for the reply, I think I got it sorted.